version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu1804
configuration: Release
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
deploy:
  - provider: NuGet
    api_key:
      secure: YZRbeAChqYmAKbSYzkiNAVHpVsRJ9/tHCni/fD9b4sqDFiZPxEqcdFwRT7hvpcBN
    username:
      secure: zzXzOxXUTcHgl6D25OJHvQ==
    on:
      branch: master
